"""Normalize the five explicitly saved Context preview sources, entirely offline.

Original files are never written. Offsets address exact Unicode strings in the
saved capture, not reserialized HTML or text generated by this normalizer.
"""
from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path

from lxml import html as lhtml

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent
SOURCES = ROOT / 'sources/judges/vendor_probe_20260914/context'
VERSION = 'context-preview-normalizer-1.0.2'
NATIVE_ID = 'cd0773bb-bfaf-49d0-a14b-58a6e85d93e7'
URL = 'https://advance.lexis.com/api/permalink/' + NATIVE_ID + '/?context=1518492'
NAME = 'Dana M. Sabraw'
FILES = {
    'overview': 'sabraw_overview.firecrawl.json',
    'motions': 'sabraw_motion_browser_final.capture.json',
    'motion_method': 'sabraw_motion_tooltip_browser.capture.json',
    'opinions': 'sabraw_citation_browser.capture.json',
    'judges': 'sabraw_cited_judges_browser.capture.json',
}
VOID = {'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr'}
SPACE = re.compile(r'\s+')


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def norm(value: str) -> str:
    return SPACE.sub(' ', value).strip()


def dump(path: Path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n', encoding='utf-8', newline='\n')


def jsonl(path: Path, rows):
    with path.open('w', encoding='utf-8', newline='\n') as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + '\n')


@dataclass
class Node:
    tag: str
    attrs: dict
    start: int
    end: int | None = None
    parent: 'Node | None' = None
    children: list = field(default_factory=list)

    def has(self, class_name):
        return class_name in self.attrs.get('class', '').split()


class IndexedHTML(HTMLParser):
    """Record literal node boundaries; never resolve URLs or execute markup."""
    def __init__(self, source):
        super().__init__(convert_charrefs=True)
        self.source = source
        self.lines = [0] + [m.end() for m in re.finditer('\n', source)]
        self.nodes = []
        self.stack = []
        self.feed(source)
        self.close()

    def source_offset(self):
        line, column = self.getpos()
        return self.lines[line - 1] + column

    def handle_starttag(self, tag, attrs):
        n = Node(tag, dict(attrs), self.source_offset(), parent=self.stack[-1] if self.stack else None)
        if n.parent:
            n.parent.children.append(n)
        self.nodes.append(n)
        if tag in VOID:
            n.end = n.start + len(self.get_starttag_text())
        else:
            self.stack.append(n)

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if self.stack and self.stack[-1].tag == tag:
            self.stack.pop().end = self.source_offset() + len(self.get_starttag_text())

    def handle_endtag(self, tag):
        for index in range(len(self.stack) - 1, -1, -1):
            if self.stack[index].tag == tag:
                end = self.source.index('>', self.source_offset()) + 1
                for n in self.stack[index:]:
                    n.end = end
                del self.stack[index:]
                return

    def fragment(self, n):
        assert n.end is not None, f'Unclosed selected node {n.tag} at {n.start}'
        return self.source[n.start:n.end]

    def element(self, n):
        return lhtml.fromstring(self.fragment(n))

    def text(self, n):
        return norm(' '.join(self.element(n).itertext()))

    def descendants(self, n, tag=None, cls=None):
        return [x for x in self.nodes if x is not n and x.start > n.start and x.end is not None
                and x.end <= n.end and (tag is None or x.tag == tag) and (cls is None or x.has(cls))]

    def visible(self, n):
        while n is not None:
            if (n.has('hidden') or 'hidden' in n.attrs or n.attrs.get('aria-hidden', '').lower() == 'true'
                    or re.search(r'display\s*:\s*none|visibility\s*:\s*hidden', n.attrs.get('style', ''), re.I)):
                return False
            n = n.parent
        return True

    def card(self, title):
        matches = [n for n in self.nodes if n.tag == 'div' and n.has('card')
                   and any(c.tag == 'h3' and self.text(c) == title for c in n.children)]
        assert len(matches) == 1, (title, len(matches))
        return matches[0]


class Capture:
    def __init__(self, key):
        self.key = key
        self.path = SOURCES / FILES[key]
        self.raw = self.path.read_bytes()
        self.digest = sha(self.raw)
        self.data = json.loads(self.raw.decode('utf-8-sig'))
        self.relpath = self.path.relative_to(ROOT).as_posix()
        self.url = self.data.get('requested_url', self.data.get('public_permalink'))
        assert self.url == URL
        if key == 'overview':
            self.pointer = '/tool_result/content/0/text'
            self.embedded_pointer = '/html'
            self.payload = json.loads(self.data['tool_result']['content'][0]['text'])
            self.text = self.payload['html']
            self.kind = 'provider_rendered_html'
            assert self.payload['metadata']['sourceURL'] == URL
        else:
            self.pointer = '/response/stdout'
            self.embedded_pointer = None
            self.text = self.data['response']['stdout']
            self.kind = 'rendered_browser_accessibility_snapshot'
            assert self.data['response']['success'] is True
        assert isinstance(self.text, str) and self.text

    def receipt(self):
        return {'source_url': self.url, 'source_path': self.relpath, 'source_sha256': self.digest,
                'source_bytes': len(self.raw),
                'captured_at': datetime.strptime(self.data['captured_at_utc'], '%Y-%m-%d %H:%M:%S UTC').replace(tzinfo=timezone.utc).isoformat(),
                'source_clock_label': self.data['captured_at_utc'],
                'capture_kind': self.kind, 'source_http_status': None,
                'decoded_text_sha256': sha(self.text.encode('utf-8')),
                'json_pointer': self.pointer, 'embedded_json_pointer': self.embedded_pointer,
                'provider_reported_http_status': self.payload['metadata'].get('statusCode') if self.key == 'overview' else None}

    def evidence(self, start, end, **extra):
        out = {'source_url': self.url, 'source_path': self.relpath, 'source_sha256': self.digest,
               'json_pointer': self.pointer, 'start': start, 'end': end, 'quote': self.text[start:end],
               'offset_basis': 'Zero-based Unicode code points in the explicitly located JSON string, end exclusive',
               'capture_kind': self.kind}
        if self.embedded_pointer:
            out['embedded_json_pointer'] = self.embedded_pointer
            out['decode_steps'] = ['Parse original UTF-8 JSON', 'Resolve json_pointer',
                                   'Parse that JSON string', 'Resolve embedded_json_pointer']
        out.update(extra)
        return out

    def html_evidence(self, indexed, n):
        fragment = indexed.fragment(n)
        return self.evidence(n.start, n.end, evidence_format='literal_html_fragment',
                             fragment_sha256=sha(fragment.encode('utf-8')),
                             literal_text=indexed.text(n), visibility='not hidden by observed node or ancestor attributes')


def fact(key, field_name, value, evidence, **extra):
    return {'fact_id': NATIVE_ID + ':' + key, 'source_observation_id': NATIVE_ID,
            'field': field_name, 'value': value, 'source_reported': True,
            'independently_verified_current': False, 'evidence': evidence, **extra}


def analysis(key, analysis_type, metric, label, value, unit, evidence, **extra):
    return {'analysis_id': NATIVE_ID + ':' + key, 'source_observation_id': NATIVE_ID,
            'metric_subject_type': 'judge', 'analysis_type': analysis_type, 'metric': metric,
            'label': label, 'value': value, 'value_as_reported': str(value), 'unit': unit,
            'period': None, 'numerator': None, 'denominator': None, 'cohort': None,
            'methodology_url': None, 'source_reported': True, 'independently_computed': False,
            'completeness': None, 'evidence': evidence, **extra}


def extract_overview(cap):
    tree = IndexedHTML(cap.text)
    facts, analyses = [], []
    header = [x for x in tree.nodes if x.tag == 'div' and x.has('centerheader')]
    assert len(header) == 1
    name = [x for x in tree.descendants(header[0], 'h1') if tree.text(x) == NAME]
    courts = tree.descendants(header[0], 'h2')
    assert len(name) == len(courts) == 1
    court = tree.text(courts[0])
    assert court == 'United States District Court, California Southern'
    facts += [fact('name', 'name', NAME, cap.html_evidence(tree, name[0])),
              fact('court-label', 'publisher_primary_court_label', court, cap.html_evidence(tree, courts[0]))]
    professional = {'judicial_experience': [], 'other_experience': [], 'education': [], 'contacts': []}
    for title, field_name in [('Judicial Experience', 'judicial_experience'), ('Other Experience', 'other_experience'), ('Education', 'education')]:
        card = tree.card(title)
        rows = tree.descendants(card, 'div', 'line-separated')
        for index, row in enumerate(rows, 1):
            assert tree.visible(row)
            left = [x for x in row.children if x.has('left')]
            right = [x for x in row.children if x.has('right')]
            assert len(left) == len(right) == 1
            parts = [tree.text(x) for x in right[0].children if x.tag in ('span', 'a')]
            time_label = tree.text(left[0]) or None
            interpretation = {}
            if field_name == 'judicial_experience':
                value = {'time_label': time_label, 'role': parts[0], 'court': parts[1],
                         'appointment_as_reported': parts[2] if len(parts) > 2 else None}
                interpretation = {'court_system': 'federal' if parts[1].startswith('United States ') else 'state',
                                  'court_system_basis': 'Normalizer classification from the explicitly named court, not a verbatim source label.',
                                  'current_service_verified': False,
                                  'present_is_publisher_literal': bool(time_label and 'Present' in time_label)}
            elif field_name == 'education':
                value = {'year_as_reported': time_label, 'institution': parts[0], 'credential': parts[1],
                         'honors': parts[2] if len(parts) > 2 else None}
            else:
                value = {'time_label': time_label, 'role': parts[0], 'employer': parts[1]}
            professional[field_name].append({'as_reported': value, 'interpretation': interpretation})
            facts.append(fact(f'{field_name}-{index}', field_name, value, cap.html_evidence(tree, row), interpretation=interpretation))
    card = tree.card('Contact')
    contact_rows = [n for n in tree.descendants(card, 'div') if any(c.has('left') for c in n.children)]
    for row in contact_rows:
        label = tree.text(next(x for x in row.children if x.has('left')))
        right = next(x for x in row.children if x.has('right'))
        if label == 'Website':
            for index, link in enumerate(tree.descendants(right, 'a'), 1):
                value = {'label': tree.text(link), 'url': link.attrs['href']}
                professional['contacts'].append({'type': 'professional_website', 'as_reported': value})
                evidence = cap.html_evidence(tree, link)
                if value['url'] not in value['label']:
                    # The visible domain omits the slash that the actual href retains.
                    literal_attr = 'href="' + value['url'] + '"'
                    at = link.start + tree.fragment(link).index(literal_attr) + len('href="')
                    evidence = [evidence, cap.evidence(at, at + len(value['url']),
                                                     evidence_format='literal_attribute_value', attribute='href')]
                facts.append(fact(f'website-{index}', 'professional_contact', value, evidence, contact_type='website'))
        else:
            assert label in ('Phone', 'Email')
            value = tree.text(right)
            professional['contacts'].append({'type': 'professional_' + label.lower(), 'as_reported': value})
            facts.append(fact(label.lower(), 'professional_contact', value, cap.html_evidence(tree, row), contact_type=label.lower()))
    card = tree.card('Opinions by Areas of Law')
    assert '(based on cases)' in tree.text(card)
    hidden, visible = [], []
    for row in tree.descendants(card, 'li'):
        label_nodes = tree.descendants(row, 'span', 'label')
        value_nodes = tree.descendants(row, 'span', 'value')
        assert len(label_nodes) == len(value_nodes) == 1
        if not tree.visible(row):
            hidden.append({'reason': 'observed hidden class/attribute; gated View More not activated',
                           'evidence': cap.html_evidence(tree, row) | {'visibility': 'hidden'}})
            continue
        label, number = tree.text(label_nodes[0]), tree.text(value_nodes[0])
        assert number.isdigit()
        visible.append(label)
        analyses.append(analysis(f'area-{len(visible)}', 'public_preview_area_of_law_count', 'opinions_by_area_of_law',
                                label, int(number), 'cases (native heading: based on cases)', cap.html_evidence(tree, row),
                                native_chart_heading='Opinions by Areas of Law', native_chart_context='(based on cases)',
                                category_overlap=None,
                                limitations=['The publisher labels these Opinions by Areas of Law (based on cases). The categories are not asserted mutually exclusive.',
                                             'Only five visible rows are normalized. Hidden rows behind View 5 More are excluded.']))
    return facts, analyses, professional, hidden, court


MOTION_RE = re.compile(r'^\s*- button "(.+?) ([0-9,]+) Cases(?: (granted|partial grant|denied))?" \[ref=([^\]]+)\]', re.M)
CITATION_RE = re.compile(r'^\s*- button "(.+?) cited ([0-9,]+) times" \[ref=([^\]]+)\]', re.M)


def require_heading(cap, heading):
    assert f'heading "{heading}' in cap.text, f'{cap.key}: required rendered heading not found'
    assert 'heading "Dana M. Sabraw"' in cap.text, f'{cap.key}: wrong judge'


def extract_motion(cap, method_cap):
    require_heading(cap, "Motion Decisions from Dana M. Sabraw's Cases")
    method_match = re.search(r'^\s*- tooltip "(.*?)"\s*$', method_cap.text, re.M)
    assert method_match and 'Motion Outcomes' in method_match.group(1)
    assert 'does not currently detect appellate reversals' in method_match.group(1)
    methodology = method_match.group(1)
    method_evidence = method_cap.evidence(method_match.start(), method_match.end())
    method_fact = fact('motion-methodology', 'vendor_motion_methodology', methodology, method_evidence,
                       typography_note='The accessibility tooltip label literally concatenates Outcomesare; source spelling is retained.')
    rows, groups = [], {}
    for m in MOTION_RE.finditer(cap.text):
        label, number, outcome, ref = m.groups()
        count = int(number.replace(',', ''))
        key = f'motion-{ref}'
        rows.append(analysis(key, 'public_preview_motion_count', 'motion_outcome_cases' if outcome else 'motion_type_cases',
                             label, count, 'Cases', cap.evidence(m.start(), m.end()), native_node_ref=ref,
                             native_chart_heading="Motion Decisions from Dana M. Sabraw's Cases",
                             motion_type=label, outcome=outcome, methodology_fact_id=method_fact['fact_id'],
                             limitations=['Native chart units are Cases; the saved methodology says Motion Outcomes are opinion-based.',
                                          'The source does not detect appellate reversals. No period, full cohort, completeness or independent outcome rate is established.']))
        group = groups.setdefault(label, {'motion_type': label, 'reported_total': None, 'total_analysis_id': None,
                                         'reported_outcomes': {'granted': None, 'partial grant': None, 'denied': None},
                                         'outcome_analysis_ids': {'granted': None, 'partial grant': None, 'denied': None}})
        if outcome is None:
            assert group['reported_total'] is None, 'Duplicate native motion total'
            group['reported_total'], group['total_analysis_id'] = count, rows[-1]['analysis_id']
        else:
            assert group['reported_outcomes'][outcome] is None, 'Duplicate native motion outcome'
            group['reported_outcomes'][outcome], group['outcome_analysis_ids'][outcome] = count, rows[-1]['analysis_id']
    assert groups and all(x['reported_total'] is not None for x in groups.values())
    match = re.search(r'^\s*- heading "([0-9,]+) cases where Dana M\. Sabraw ruled on a motion to dismiss Information tooltip"[^\n]*', cap.text, re.M)
    assert match
    rows.append(analysis('motion-dismiss-results-count', 'public_preview_result_list_count', 'motion_case_result_list_count',
                         'Cases where Dana M. Sabraw ruled on a motion to dismiss (result-list heading)',
                         int(match.group(1).replace(',', '')), 'cases', cap.evidence(match.start(), match.end()),
                         motion_type='motion to dismiss', separate_from_chart_total=True,
                         limitations=['This result-list count is distinct from the native motion-to-dismiss chart total; neither is used to calculate a rate.',
                                      'The saved result-list document previews are not normalized or followed.']))
    return rows, list(groups.values()), method_fact


def extract_citations(cap, referenced_type):
    require_heading(cap, 'Frequently Cited')
    rows = []
    for index, m in enumerate(CITATION_RE.finditer(cap.text), 1):
        label, number, ref = m.groups()
        rows.append(analysis(f'cited-{referenced_type}-{ref}', 'public_preview_citation_frequency',
                             f'cited_{referenced_type}_frequency', label, int(number.replace(',', '')), 'times',
                             cap.evidence(m.start(), m.end()), native_node_ref=ref, native_chart_heading='Frequently Cited',
                             native_display_position=index, referencing_judge=NAME,
                             referenced_entity={'display_name': label, 'entity_type': referenced_type,
                                                'resolved_identity': None, 'match_status': 'display_label_only_no_cross_source_merge'},
                             methodology=None,
                             limitations=['The frequency is attributed to the citing judge Dana M. Sabraw, not performance of the referenced entity.',
                                          'Duplicate display labels remain separate native graph records. Period, citation corpus and completeness are unknown.',
                                          'Underlying result-list documents and their text are excluded from normalization.']))
    assert rows
    return rows


def resolve_pointer(obj, pointer):
    for part in pointer.lstrip('/').split('/'):
        part = part.replace('~1', '/').replace('~0', '~')
        obj = obj[int(part)] if isinstance(obj, list) else obj[part]
    return obj


def validate_evidence(evidence, receipts):
    if isinstance(evidence, list):
        assert evidence
        for item in evidence:
            validate_evidence(item, receipts)
        return
    p = (ROOT / evidence['source_path']).resolve()
    assert p.is_relative_to(ROOT.resolve())
    raw = p.read_bytes()
    assert sha(raw) == evidence['source_sha256'] == receipts[evidence['source_path']]['source_sha256']
    located = resolve_pointer(json.loads(raw.decode('utf-8-sig')), evidence['json_pointer'])
    if evidence.get('embedded_json_pointer'):
        located = resolve_pointer(json.loads(located), evidence['embedded_json_pointer'])
    assert isinstance(located, str)
    start, end = evidence['start'], evidence['end']
    assert isinstance(start, int) and isinstance(end, int) and 0 <= start < end <= len(located)
    assert located[start:end] == evidence['quote']
    if evidence.get('fragment_sha256'):
        assert sha(evidence['quote'].encode('utf-8')) == evidence['fragment_sha256']
        assert norm(' '.join(lhtml.fromstring(evidence['quote']).itertext())) == evidence['literal_text']


def build():
    captures = {k: Capture(k) for k in FILES}
    receipts = {c.relpath: c.receipt() for c in captures.values()}
    facts, analyses, professional, hidden, court = extract_overview(captures['overview'])
    motions, groups, method = extract_motion(captures['motions'], captures['motion_method'])
    facts.append(method)
    analyses += motions + extract_citations(captures['opinions'], 'opinion') + extract_citations(captures['judges'], 'judge')
    observation = {'source_observation_id': NATIVE_ID, 'name': NAME, 'subject_type': 'judge',
                   'record_class': 'public_ui_preview', 'publisher': 'LexisNexis Context',
                   'source_class': 'public_vendor_preview_profile', 'judge_system': 'federal',
                   'judge_system_basis': 'The overview header explicitly names United States District Court; former California state service is retained separately.',
                   'state_code': 'CA', 'state': 'California', 'courts': [court], 'counties': None,
                   'state_basis': 'California is explicitly in the source court heading; no county is assigned from former state-court service.',
                   **captures['overview'].receipt(), 'additional_sources': [c.receipt() for k, c in captures.items() if k != 'overview'],
                   'current_service_verified': False, 'current_status': None,
                   'identity_resolution': 'native public permalink only; no name-based cross-source merge',
                   'professional_fields': professional,
                   'limitations': ['Public free preview; source-reported limited vendor corpus, not independently verified current judicial service.',
                                   'No period, complete opinion/case universe, pagination completeness or underlying case cohort is established.',
                                   'Five hidden area-of-law rows and the unquantified Opinions Per Year graphic are not normalized.',
                                   'Motion-chart Cases counts and the separate result-list count are retained distinctly.',
                                   'Source contacts and Present service wording may be stale; no current verification was performed.']}
    assert len(facts) == 15
    assert len(groups) == 116
    assert sum(x['metric'] == 'motion_outcome_cases' for x in analyses) == 228
    assert sum(x['metric'] == 'cited_opinion_frequency' for x in analyses) == 50
    assert sum(x['metric'] == 'cited_judge_frequency' for x in analyses) == 49
    assert len(hidden) == 5
    assert len(analyses) == 449
    assert len({x['analysis_id'] for x in analyses}) == len(analyses)
    assert len({x['fact_id'] for x in facts}) == len(facts)
    for record in facts + analyses:
        assert record['source_observation_id'] == NATIVE_ID
        validate_evidence(record['evidence'], receipts)
    for row in hidden:
        validate_evidence(row['evidence'], receipts)
    for a in analyses:
        assert a['metric_subject_type'] == 'judge' and a['source_reported'] is True and a['independently_computed'] is False
        assert all(a[key] is None for key in ('period', 'numerator', 'denominator', 'cohort', 'methodology_url', 'completeness'))
    fixture_checks(analyses, groups, facts, captures)
    for c in captures.values():
        assert sha(c.path.read_bytes()) == c.digest, 'Original changed during offline build'
    OUT.mkdir(parents=True, exist_ok=True)
    jsonl(OUT / 'observations.jsonl', [observation])
    jsonl(OUT / 'facts.jsonl', facts)
    jsonl(OUT / 'analyses.jsonl', analyses)
    jsonl(OUT / 'source_documents.jsonl', list(receipts.values()))
    jsonl(OUT / 'motion_breakdowns.jsonl', groups)
    jsonl(OUT / 'exclusions.jsonl', hidden + [
        {'reason': 'Only axis text is exposed for Opinions Per Year; no reliable data series is captured.', 'source_path': captures['overview'].relpath, 'source_sha256': captures['overview'].digest},
        {'reason': 'The earlier post-click file still shows Overview, and is not used as a Motion source.', 'path': (SOURCES / 'sabraw_motion_browser.capture.json').relative_to(ROOT).as_posix()},
        {'reason': 'Citation tooltip click supplied no explanatory methodology text; no citation methodology is inferred.', 'path': (SOURCES / 'sabraw_citation_tooltip_browser.capture.json').relative_to(ROOT).as_posix()},
        {'reason': 'Case-result previews, document snippets, downloads, identity controls, navigation and device warning headings are outside normalized preview scope.'}])
    counts = dict(Counter(x['metric'] for x in analyses))
    summary = {'generated_at': datetime.now(timezone.utc).isoformat(), 'normalizer': VERSION,
               'observations': 1, 'facts': len(facts), 'analyses': len(analyses), 'analysis_counts': counts,
               'source_originals': len(captures), 'motion_types': len(groups), 'explicit_outcomes': 228,
               'missing_outcome_buttons': sum(v is None for g in groups for v in g['reported_outcomes'].values()),
               'visible_areas': 5, 'hidden_areas_excluded': len(hidden), 'current_service_verified': False,
               'period': None, 'cohort': None, 'completeness': None, 'network_requests_by_normalizer': 0,
               'source_access': 'Public free preview, no account credentials supplied',
               'not_full_corpus_or_current_analytics': True}
    dump(OUT / 'summary.json', summary)
    output_sha256 = {p.name: sha(p.read_bytes()) for p in sorted(OUT.glob('*.jsonl'))}
    validation = {'validated': True, 'status': 'passed', 'normalizer': VERSION,
                  'validated_at': datetime.now(timezone.utc).isoformat(), 'output_sha256': output_sha256,
                  'original_receipts': list(receipts.values()), 'counts': summary,
                  'checks': {'literal_evidence_records': len(facts) + len(analyses), 'excluded_html_evidence_records': len(hidden),
                             'all_original_bytes_unchanged': True, 'all_source_urls_match_native_permalink': True,
                             'all_evidence_path_hash_and_unicode_slices_reproduce': True,
                             'all_analysis_subjects_are_citing_judge': True, 'unknown_contexts_remain_null': True,
                             'unique_record_ids': True, 'focused_semantic_checks': 13},
                  'unresolved_findings': [],
                  'limitations': ['Validation certifies extraction from these five saved preview captures only; it does not validate the vendor underlying cases, current judge service, complete corpus or metric methodology.']}
    dump(OUT / 'validation.json', validation)
    print(json.dumps({'validated': True, 'counts': summary, 'output_sha256': output_sha256}, ensure_ascii=True))


def fixture_checks(analyses, groups, facts, captures):
    """Focused actual-source regressions; no requests and no synthetic metrics."""
    by = {g['motion_type']: g for g in groups}
    assert by['motion to dismiss']['reported_total'] == 542
    assert by['motion to dismiss']['reported_outcomes'] == {'granted': 262, 'partial grant': 156, 'denied': 124}
    assert next(x for x in analyses if x['metric'] == 'motion_case_result_list_count')['value'] == 489
    assert by['motion for remand']['reported_outcomes']['partial grant'] is None
    assert by['motion for sanctions']['reported_outcomes']['granted'] is None
    assert [x['value'] for x in analyses if x['metric'] == 'cited_opinion_frequency' and x['label'] == 'Andrews v. Cervantes'] == [72, 71]
    assert [x['value'] for x in analyses if x['metric'] == 'cited_judge_frequency' and x['label'] == NAME] == [217]
    assert [x['value'] for x in analyses if x['metric'] == 'cited_judge_frequency' and x['label'] == 'Anthony M. Kennedy'] == [834]
    areas = [(x['label'], x['value']) for x in analyses if x['metric'] == 'opinions_by_area_of_law']
    assert areas == [('Civil Procedure', 2023), ('Business & Corporate Compliance', 1211), ('Governments', 991), ('Torts', 948), ('Constitutional Law', 844)]
    assert not any(x['metric'] == 'opinions_per_year' for x in analyses)
    education = [x['value'] for x in facts if x['field'] == 'education']
    assert [x['year_as_reported'] for x in education] == ['1985', '1980', '1978']
    assert len([x for x in facts if x['field'] == 'judicial_experience' and x['interpretation']['court_system'] == 'state']) == 1
    # The saved post-click capture was still Overview, so a Motion extractor must reject it.
    old = json.loads((SOURCES / 'sabraw_motion_browser.capture.json').read_text(encoding='utf-8-sig'))
    assert "heading \"Motion Decisions from Dana M. Sabraw's Cases" not in old['response']['stdout']


if __name__ == '__main__':
    build()
